# Generated by Django 6.0.6 on 2026-06-23 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('tagline', models.CharField(max_length=255, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
                ('population', models.CharField(max_length=50, verbose_name='Население')),
                ('best_time', models.CharField(max_length=100, verbose_name='Лучшее время для визита')),
                ('accent', models.CharField(default='#00afca', max_length=7, verbose_name='HEX-цвет акцента')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на фото города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название места')),
                ('description', models.TextField(verbose_name='Описание места')),
                ('category', models.CharField(choices=[('museum', 'Музей 🏛️'), ('hotel', 'Отель 🏨'), ('restaurant', 'Ресторан 🍽️'), ('nature', 'Природа 🌳'), ('history', 'История 🏰')], max_length=30, verbose_name='Категория')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на фото места')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='main.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Интересное место',
                'verbose_name_plural': 'Интересные места',
            },
        ),
    ]
